ALTER TABLE `ApiToken`
  CHANGE COLUMN `abilities` `permissions` JSON NOT NULL,
  ADD COLUMN `preview` VARCHAR(191) NOT NULL DEFAULT '',
  ADD COLUMN `status` ENUM('ACTIVE', 'REVOKED', 'EXPIRED') NOT NULL DEFAULT 'ACTIVE';
